Microsoft.Data.SqlClient.SqlException: 'Column 'TblArtist.RecordLabel_ID' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.'